# Generated by Django 5.1.4 on 2024-12-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='contact',
            new_name='content',
        ),
    ]
