# Generated by Django 5.1.4 on 2024-12-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_contact_features_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(to='services.category'),
        ),
        migrations.AddField(
            model_name='services',
            name='content',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='options',
            field=models.ManyToManyField(to='services.options'),
        ),
        migrations.DeleteModel(
            name='Services_details',
        ),
    ]
