# Generated by Django 5.1.4 on 2024-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countstars',
            name='count',
            field=models.IntegerField(default=5),
        ),
    ]
