# Generated by Django 5.1.4 on 2024-12-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fqa',
            old_name='questin',
            new_name='question',
        ),
    ]
